name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f47b099ee9e96a7a676db1f94f1248e7754003bc464dcf772625b50fb6d2e98b"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
