name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "205d8531f335341180792bf4bcda2ba480b8963b12929e5678726317741dc99e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
