name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca612814d6da0a001077668780497643ad4a47ce35cf08a3f48dfd59605d2d8a"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
