name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bdc07571e39fd5098253c214b791579360a07e4682c88e9d2224523f78e29abe"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
