name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93bfa83f586ce8c0e5839549c03a6552a0843c34925ec8eaff54d61a6cfd711d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
