name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cca3c3311cc8179d10a0fbb6f2c53c99ded5e14f68b62b69b363733c22e32702"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
