name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "927be0ab87991073340afb2e8500ba94e8a348ecfd5bd25a62bb98943b59f977"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
