name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a102e218f12a483c074b8e942adc9bc8899432b65fa6b59ef1839ccb3e151ab0"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
