name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fee0caa4754f60ef0e9e992c90b7ea5a8bc64c7e51ee2bde533bfdfb46b0b19e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
