name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f253272b9609d4f7fc078f187e66fa65f9173cd810bc3ad36fbcfd2679f021c"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
