name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cf5b4f5b5965af377d9b3ba94a2decff147736c0110a2e15d0462948c6b48fc"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
