name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "348cc264a2868fa04bc01a655858c7081712c711bd4a475c1b0676bd8bc497b4"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
