name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "273eab2500952aa7bc67c40cf00b703235d264d9bb3a5168ab22df2154ea82c8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
