name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee07d512597084e1079b120676054f4b8e12ab3ae1d252560cb0c1ce9556b82f"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
