name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be146444fb70b28ea67184fafbc4877a4934bcdb063870f837b4e759873f84e1"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
