name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48049039d716389016785701f6b8deb2942cf19a53cbb2972abad1affb21a690"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
