name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35151a370566ad8b95cfd17ebd7c116e9df0d62df8b23757962302634dde37b8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
