name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "465feee7e9c7a7a83c3af704801214fa990f9913c89d9f20d4cb4d9891afe99e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
