name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72c1707f8cb6d6f2ea2ae89ee1d1a54c3f8539b81ce69a5fa1daa6a6ea89604a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
