name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3ea8704bcd98f111e66aa4aada1c402103717afadb4b093ba4eb33fa20ec585"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
