name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b964e2fe93b5986c2211e03a8f4ff008995f17408a1440b273613582dea8ae2"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
