name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd10d6d9807fd55e6f3451cd62c559bc542877cc4ca8e650137dba4724b21a6a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
