name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f4e654c771bc4f77d0d8164fa3ff36cd4c9482c66c98d0667380e355f26506c"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
