name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3138386e5f88ce43778899e28fbdb39b7ca2077fd34262f9c9214deba88fe699"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
