name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b97f344d4c477c4fe1319266154f9620203a2e5e6439889283585f7131acf9f"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
