name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca7a8f7acef470cb2a7921fbce5e80fd732db27bc7728d30380b7c2043c2f059"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
