name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8684bcd908e80991b14f42c3a56e3da040de92a8d111c2f2cc58330c993587c7"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
