name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "504df64122e35a8d8b5600e264d76bac526c383441cbbb5178d053192294fce6"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
