name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0a1d7151b186b9dcaba00709f061e41cba9e567ca3c50d772c030a3e68c0415"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
