name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8b6bb08fdf9b0c2ebfb9fa3f147fdf6ae759d443fb7945130cf85830b9e7d43"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
