name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7865105c1ab489cf9243d24df09e6a66c8bc276bba1513e3ca822fba6e6b8ced"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
