name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44013243cba95a0d24cf6c9793eeb584f94f8178d010ff14165f309f47758117"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
