name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d94319770e52570df9ca719cdd9e5dccd35c56834046cb41a721435e809735d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
