name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac05db7d97390e8a9e1a16070cafde7970055fba024e0fdeb3374769aeb9a54e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
