name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d13726c46dc5530e4b856e797d71fa6160541d2fcf7038aa4fa5d6170bfb98e7"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
