name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "491584844eab9411ccebc7036bac261b9cf9a3a9129fe6d98c6a7b2d9d9ca159"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
