name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02087785aa92791055bc40dace6aa57b591bdfabb565c791d2ed671e83956374"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
