name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5faa093108e31683c7d891778d48762c71d6663325c81d327fa1694bf8e019c0"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
