name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "011b2702cf22987141989c26330a50d03673cbd9551a434a1e9e6cdb2bcf522f"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
