name = "LaW Minecraft"
author = "Shahmi"
version = "3.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1c2558313b08ffe5eadd174c52564138bb2d7e0560ac7371f1a43719cd01d6c"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
