name = "Better SMC"
author = "Shahmi"
version = "2.2.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad7bd12d74f58118d778d24659e6b2e1055f98622acc02b47ad2d97c403a744d"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
