name = "LaW Minecraft"
author = "Shahmi"
version = "1.0.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b78e830614295822393af4467655e387c25dbb7790f016cb97d1b1560e5a5e66"

[versions]
fabric = "0.13.2"
minecraft = "1.18.1"
