name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0015757fc93c14758eed469fc2e8bd63024699f3ba504595e6a54e9874ef1ab9"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
