name = "LaW Minecraft"
author = "Shahmi"
version = "2.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e92635d03dbe58b3c013ad9247d95fdf8fb147df7075c86e61f47df9ae5feb78"

[versions]
fabric = "0.13.3"
minecraft = "1.18.1"
