name = "Stay True"
filename = "Stay_True_1.18.zip"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3598/573/Stay_True_1.18.zip"
hash-format = "sha1"
hash = "39a4638db2c2acddeadf4c0b8c36ad317fc51d7a"

[update]
[update.curseforge]
file-id = 3598573
project-id = 353554
