name = "Sildur's Enhanced Default"
filename = "Sildur's+Enhanced+Default+v1.131+Fast.zip"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3590/066/Sildur's+Enhanced+Default+v1.131+Fast.zip"
hash-format = "sha1"
hash = "dff89d90c6de80cf890c1a4e8e553afdaa55f16f"

[update]
[update.curseforge]
file-id = 3590066
project-id = 544140
