name = "Additional Additions"
filename = "AdditionalAdditions-3.0.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/R4TvILfj/versions/3.0.1/AdditionalAdditions-3.0.1.jar"
hash-format = "sha1"
hash = "181a29a8b509bd46493ead546c186188edcd55b3"

[update]
[update.modrinth]
mod-id = "R4TvILfj"
version = "BmwSZmFM"
