name = "Additional Bars"
filename = "1.18.2-additionalbars-3.0.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/hgNzwsf3/versions/3.0.0/1.18.2-additionalbars-3.0.0.jar"
hash-format = "sha1"
hash = "9829ea8210d65c7ca07856ce185d139ae0d524ab"

[update]
[update.modrinth]
mod-id = "hgNzwsf3"
version = "OOUxw3Zt"
