name = "Architectury API (Fabric)"
filename = "architectury-3.7.33.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3705/892/architectury-3.7.33.jar"
hash-format = "sha1"
hash = "9ce81c4ba50d617a2a062550745508a133bb4938"

[update]
[update.curseforge]
file-id = 3705892
project-id = 419697
