name = "Architectury API (Fabric)"
filename = "architectury-3.7.37.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3717/908/architectury-3.7.37.jar"
hash-format = "sha1"
hash = "2e310eceffd4b73d81ef0e521b6660d9d9e0502e"

[update]
[update.curseforge]
file-id = 3717908
project-id = 419697
