name = "Awesome Dungeon Ocean edition - Fabric"
filename = "AwesomeDungeonOcean-Fabric-1.18-2.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3631/165/AwesomeDungeonOcean-Fabric-1.18-2.0.5.jar"
hash-format = "sha1"
hash = "7f46452287908703473e9bfb60fbf9dfcdee4f36"

[update]
[update.curseforge]
file-id = 3631165
project-id = 556489
