name = "Awesome Dungeon The End edition - Fabric"
filename = "AwesomeDungeonEnd-Fabric-1.18.1-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3647/791/AwesomeDungeonEnd-Fabric-1.18.1-1.0.0.jar"
hash-format = "sha1"
hash = "327639feeb1ebd41efd9dfdd7505416953f1a0b8"

[update]
[update.curseforge]
file-id = 3647791
project-id = 575402
