name = "Awesome Dungeon Nether edition - Fabric"
filename = "AwesomeDungeonNether-Fabric-1.18.1-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3629/487/AwesomeDungeonNether-Fabric-1.18.1-1.0.0.jar"
hash-format = "sha1"
hash = "01cce824c69be69b54945569e8f6ac9f6e0f93e4"

[update]
[update.curseforge]
file-id = 3629487
project-id = 566642
