name = "BetterLoadingScreen"
filename = "better-loading-screen-1.2.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3697/289/better-loading-screen-1.2.1.jar"
hash-format = "md5"
hash = "bc0ef6ea0576e0ebb9ee616364288bfc"

[update]
[update.curseforge]
file-id = 3697289
project-id = 594044