name = "Better Azalea"
filename = "azalea-FABRIC-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3621/108/azalea-FABRIC-1.0.1.jar"
hash-format = "sha1"
hash = "e29ee80aad7471f1028e5e8ff4c223eedfd7dda8"

[update]
[update.curseforge]
file-id = 3621108
project-id = 517564
