name = "BetterF3"
filename = "BetterF3-1.2.3-Fabric-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/534/BetterF3-1.2.3-Fabric-1.18.2.jar"
hash-format = "sha1"
hash = "3ab9b1ed6c043cb87a36bf44788502dde2601e2c"

[update]
[update.curseforge]
file-id = 3667534
project-id = 401648
