name = "BetterLoadingScreen"
filename = "better-loading-screen-1.2.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3695/622/better-loading-screen-1.2.0.jar"
hash-format = "sha1"
hash = "93ed0eeab379c14a0cfebb415282196aa6d9397d"

[update]
[update.curseforge]
file-id = 3695622
project-id = 594044
