name = "Better Loading Screen"
filename = "better-loading-screen-1.3.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3710/581/better-loading-screen-1.3.1.jar"
hash-format = "sha1"
hash = "dec65232aa4a818d99a14cc6e3288b5b1972fdaa"

[update]
[update.curseforge]
file-id = 3710581
project-id = 594044
