name = "Biome Particle Weather"
filename = "BiomeParticleWeather-2.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3721/981/BiomeParticleWeather-2.3.5.jar"
hash-format = "sha1"
hash = "2f80e511ebcd97326adaaeeea198c0d023d05b68"

[update]
[update.curseforge]
file-id = 3721981
project-id = 575109
