name = "Biome Particle Weather"
filename = "BiomeWeatherEffects-1.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3662/319/BiomeWeatherEffects-1.3.2.jar"
hash-format = "sha1"
hash = "a024da49f4b6cad99f54005b4b9697c98fdc7f41"

[update]
[update.curseforge]
file-id = 3662319
project-id = 575109
