name = "Blockus"
filename = "blockus-2.3.7+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3693/338/blockus-2.3.7+1.18.1.jar"
hash-format = "sha1"
hash = "8738b9a29ab2ca835ca0b64a64d0bdcbb895cdb0"

[update]
[update.curseforge]
file-id = 3693338
project-id = 312289
