name = "Blockus"
filename = "blockus-2.3.8+1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3696/864/blockus-2.3.8+1.18.1.jar"
hash-format = "sha1"
hash = "a73ea7bef81164d12c2daccbabb69a18ee93ef7f"

[update]
[update.curseforge]
file-id = 3696864
project-id = 312289
