name = "Blockus"
filename = "blockus-2.4.1+1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3706/789/blockus-2.4.1+1.18.2.jar"
hash-format = "sha1"
hash = "041350023d5343c7e23ba9c3266851c1da4359e4"

[update]
[update.curseforge]
file-id = 3706789
project-id = 312289
