name = "Bountiful (Fabric)"
filename = "BountifulFabric-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3599/391/BountifulFabric-2.0.2.jar"
hash-format = "sha1"
hash = "3cb3a1006331ad854592bcbfae07d314476ccea3"

[update]
[update.curseforge]
file-id = 3599391
project-id = 521673
