name = "Bow Infinity Fix (Forge/Fabric)"
filename = "BowInfinityFix-1.18.x-fabric-rv11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3546/225/BowInfinityFix-1.18.x-fabric-rv11.jar"
hash-format = "sha1"
hash = "453b32efe1e602e22f1472bbf4ee2286b1367939"

[update]
[update.curseforge]
file-id = 3546225
project-id = 224713
