name = "CameraOverhaul"
filename = "CameraOverhaul-1.3.0-fabric-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3498/10/CameraOverhaul-1.3.0-fabric-universal.jar"
hash-format = "sha1"
hash = "beebe8078d9a3faf3a9534213da082a5adf9a873"

[update]
[update.curseforge]
file-id = 3498010
project-id = 423602
