name = "Camp Chair"
filename = "campchair-fabric.1.18.2-1.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/467/campchair-fabric.1.18.2-1.0.0.jar"
hash-format = "sha1"
hash = "88d1ffd9fd7953a3c938d4975a2214b01b9188ab"

[update]
[update.curseforge]
file-id = 3669467
project-id = 531744
