name = "Caracal Mod (Fabric/Forge)"
filename = "caracal-1.18-1.3.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3709/593/caracal-1.18-1.3.7.1.jar"
hash-format = "sha1"
hash = "7a351e278c23dfe9a74fdb34817d0a840edbed08"

[update]
[update.curseforge]
file-id = 3709593
project-id = 486505
