name = "Caracal Mod (Fabric/Forge)"
filename = "caracal-1.18.2-1.3.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/765/caracal-1.18.2-1.3.6.jar"
hash-format = "sha1"
hash = "af08eced9f3c781bf4effb0aea2a6a9c744dfcf7"

[update]
[update.curseforge]
file-id = 3681765
project-id = 486505
