name = "CC: Restitched"
filename = "cc-restitched-1.100.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/662/cc-restitched-1.100.3.jar"
hash-format = "sha1"
hash = "1b35277d6c63d4431cdd69dc890a35764783185f"

[update]
[update.curseforge]
file-id = 3725662
project-id = 462672
