name = "Craftable Horse Armour & Saddle [CHA&S]"
filename = "CHAS-1.18-1.8-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/387/CHAS-1.18-1.8-Fabric.jar"
hash-format = "sha1"
hash = "69dd9766e1796af275dfaafaa395b4fa88848710"

[update]
[update.curseforge]
file-id = 3542387
project-id = 224841
