name = "Chicken Drop Feathers"
filename = "ChickenDropFeathers-1.0-fabric-0.46.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3617/105/ChickenDropFeathers-1.0-fabric-0.46.2+1.18.jar"
hash-format = "sha1"
hash = "ed3b396ff78409561190820ae0a242dcbcfe0118"

[update]
[update.curseforge]
file-id = 3617105
project-id = 300374
