name = "Clickable advancements[Forge/Fabric]"
filename = "clickadv-fabric-2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/4/clickadv-fabric-2.5.jar"
hash-format = "sha1"
hash = "7d8c221ea3397b785288725ec4069f338c7e433a"

[update]
[update.curseforge]
file-id = 3672004
project-id = 511733
