name = "Columns"
filename = "columns-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/332/columns-1.3.0.jar"
hash-format = "sha1"
hash = "0dc4b9668182d1145022f8fc5a525657d550f59f"

[update]
[update.curseforge]
file-id = 3667332
project-id = 385230
