name = "Columns"
filename = "columns-1.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3697/328/columns-1.4.0.jar"
hash-format = "sha1"
hash = "99ecb175cb5b827f8e30ceca2a0e7e31de98ed44"

[update]
[update.curseforge]
file-id = 3697328
project-id = 385230
