name = "Creatures From The Snow! [Fabric]"
filename = "CreaturesFromTheSnow+0.0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3662/607/CreaturesFromTheSnow+0.0.7.jar"
hash-format = "sha1"
hash = "81704666cd619fee5037db04372189257b601c6a"

[update]
[update.curseforge]
file-id = 3662607
project-id = 576413
