name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.18.2-FABRIC-1.8.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/796/Croptopia-1.18.2-FABRIC-1.8.1.jar"
hash-format = "sha1"
hash = "6a6a013a71ec4dd860e065b086e911f14ee3d537"

[update]
[update.curseforge]
file-id = 3667796
project-id = 415438
