name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.18.2-FABRIC-1.8.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/656/Croptopia-1.18.2-FABRIC-1.8.3.jar"
hash-format = "sha1"
hash = "7b5045e038394407742bf4612b76110b02bea107"

[update]
[update.curseforge]
file-id = 3707656
project-id = 415438
