name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.18-FABRIC-1.8.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/479/Croptopia-1.18-FABRIC-1.8.2.jar"
hash-format = "sha1"
hash = "3c53ea03fee2e8085a24fd24548c2dda0d1bbe3c"

[update]
[update.curseforge]
file-id = 3671479
project-id = 415438
