name = "CustomSkinLoader"
filename = "CustomSkinLoader_Fabric-14.13-SNAPSHOT-317.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3670/754/CustomSkinLoader_Fabric-14.13-SNAPSHOT-317.jar"
hash-format = "sha1"
hash = "dc657ad0a597a84924883e0de5e93bc70256e58b"

[update]
[update.curseforge]
file-id = 3670754
project-id = 286924
