name = "CustomSkinLoader"
filename = "CustomSkinLoader_Fabric-14.14-SNAPSHOT-321.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3726/256/CustomSkinLoader_Fabric-14.14-SNAPSHOT-321.jar"
hash-format = "sha1"
hash = "6d94ab3df050576b3fa7df579eaac84ee7addd91"

[update]
[update.curseforge]
file-id = 3726256
project-id = 286924
