name = "Cycle Paintings (Fabric)"
filename = "cyclepaintings-fabric_1.18.x-2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/288/cyclepaintings-fabric_1.18.x-2.1.jar"
hash-format = "sha1"
hash = "d0a6cbc743673dc5ffc76635305827f33d66081a"

[update]
[update.curseforge]
file-id = 3542288
project-id = 531272
