name = "Damage Tilt"
filename = "DamageTilt-1.18-fabric-0.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/92/DamageTilt-1.18-fabric-0.1.2.jar"
hash-format = "sha1"
hash = "eba4981816551b400fae1d5ad7acfb8feb19b722"

[update]
[update.curseforge]
file-id = 3548092
project-id = 411705
