name = "DashLoader"
filename = "dashloader-def-3.0.1+1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/ZfQ3kTvR/versions/3.0.1+1.18/dashloader-def-3.0.1%2B1.18.jar"
hash-format = "sha1"
hash = "28fa55db839e36a0599278a46412f9dfcf926355"

[update]
[update.modrinth]
mod-id = "ZfQ3kTvR"
version = "xps3tiEt"
