name = "Dawn API"
filename = "dawn-3.2.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/meZK2DCX/versions/3.2.0/dawn-3.2.0.jar"
hash-format = "sha1"
hash = "84846a6a9ae738a9ba3faf7e552dd844df42c850"

[update]
[update.modrinth]
mod-id = "meZK2DCX"
version = "xzF6wvdF"
