name = "Dimension Fix (Some Forge Patches Ported)"
filename = "someforgepatchesported-1.0.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ENoifro7/versions/1.0.2/someforgepatchesported-1.0.2.jar"
hash-format = "sha1"
hash = "faa83cff5b97e832f9f1b8599931cd1d5e17521a"

[update]
[update.modrinth]
mod-id = "ENoifro7"
version = "hvt7k7i5"
