name = "Disenchanter"
filename = "disenchanter-0.1.4+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3581/850/disenchanter-0.1.4+1.18.jar"
hash-format = "sha1"
hash = "a133b14601819b58623d5d2c188371cb1ff71846"

[update]
[update.curseforge]
file-id = 3581850
project-id = 542473
