name = "Disenchanter"
filename = "disenchanter-0.1.5+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/OQ8To4FT/versions/0.1.5+1.18/disenchanter-0.1.5+1.18.jar"
hash-format = "sha1"
hash = "43038ccf965cf36ac14ba3f9656ddc3ee7d9f22a"

[update]
[update.modrinth]
mod-id = "OQ8To4FT"
version = "BsyhO78u"
