name = "Double Doors (Fabric)"
filename = "doubledoors-fabric_1.18.x-3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3544/358/doubledoors-fabric_1.18.x-3.1.jar"
hash-format = "sha1"
hash = "c1f9d93ce148aa6c19ef2cec8145720f58f1d5bd"

[update]
[update.curseforge]
file-id = 3544358
project-id = 541214
