name = "Dynamic Sound Filters"
filename = "DynamicSoundFilters-1.3.0+1.18.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3531/612/DynamicSoundFilters-1.3.0+1.18.jar"
hash-format = "sha1"
hash = "f13f787d0f38e7e75959fabde1334d7ea3c9a444"

[update]
[update.curseforge]
file-id = 3531612
project-id = 392101
