name = "Easy Magic [Fabric]"
filename = "EasyMagic-v3.2.1-1.18.1-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3580/168/EasyMagic-v3.2.1-1.18.1-Fabric.jar"
hash-format = "sha1"
hash = "2e24dca092014c3058d2b5dcda9f4a7b683801e1"

[update]
[update.curseforge]
file-id = 3580168
project-id = 547471
