name = "Economical Villager Trading"
filename = "economical-villager-trading-1.2.5+MC1.18-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3694/716/economical-villager-trading-1.2.5+MC1.18-1.18.2.jar"
hash-format = "sha1"
hash = "d07b74be10f52c601e144b38354cfeced35bd79a"

[update]
[update.curseforge]
file-id = 3694716
project-id = 395573
