name = "Egg Of Capitalism"
filename = "egg-of-capitalism-mc1.18-3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/llThBwQo/versions/mc1.18-3.0/egg-of-capitalism-mc1.18-3.0.jar"
hash-format = "sha1"
hash = "138e2ea327fbe2b2a115ecf81aff65380cbbc7df"

[update]
[update.modrinth]
mod-id = "llThBwQo"
version = "mwt75pjt"
