name = "Exline's Furniture Mod"
filename = "exlinefurniture-fabric-1.18.2-v2.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/232/exlinefurniture-fabric-1.18.2-v2.0.5.jar"
hash-format = "sha1"
hash = "721c1a83a3dd3c957b9e441d8347ee52a1b47700"

[update]
[update.curseforge]
file-id = 3683232
project-id = 504919
