name = "Fabric Shield Lib"
filename = "FabricShieldLib-1.5.0-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3637/448/FabricShieldLib-1.5.0-1.18.jar"
hash-format = "sha1"
hash = "dd233d1ee4944c06133fd66bcd7514ced91e549e"

[update]
[update.curseforge]
file-id = 3637448
project-id = 380649
