name = "[Fabric] Extended Armor Bars Forked"
filename = "extended-armor-bars-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/156/extended-armor-bars-1.1.0.jar"
hash-format = "sha1"
hash = "ea776bb376233135be29a13806918a31d1574742"

[update]
[update.curseforge]
file-id = 3606156
project-id = 567580
