name = "Fabric Waystones"
filename = "wraith-waystones-2.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/744/wraith-waystones-2.4.1.jar"
hash-format = "sha1"
hash = "4b407e9d050b881bea1a454521b721e69380fb02"

[update]
[update.curseforge]
file-id = 3575744
project-id = 410902
