name = "Fabric Shield Lib"
filename = "FabricShieldLib-1.5.3-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/635/FabricShieldLib-1.5.3-1.18.jar"
hash-format = "sha1"
hash = "c22c399da855d37eb0020ba585bf47e019cf3e5a"

[update]
[update.curseforge]
file-id = 3672635
project-id = 380649
