name = "Flonters"
filename = "Flonters-1.3.0+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/36iNFpQE/versions/1.3.0/Flonters-1.3.0+1.18.1.jar"
hash-format = "sha1"
hash = "4efed4095d876c15927f92c20c51cf600ad33c59"

[update]
[update.modrinth]
mod-id = "36iNFpQE"
version = "3oEntfZm"
