name = "FPS - Display"
filename = "fpsdisplay-1.4.2+1.18.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/DIlqwRFH/versions/1.4.2+1.18/fpsdisplay-1.4.2+1.18.jar"
hash-format = "sha1"
hash = "e95e9edcd39c5d50eb71ce638c1da545152c25ef"

[update]
[update.modrinth]
mod-id = "DIlqwRFH"
version = "YEcfKfAo"
