name = "Friends&Foes [Fabric]"
filename = "friendsandfoes-mc1.18.2-1.2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3668/804/friendsandfoes-mc1.18.2-1.2.6.jar"
hash-format = "sha1"
hash = "638fbf3fa32e26933796e7e3b7371b9bf953c01f"

[update]
[update.curseforge]
file-id = 3668804
project-id = 551364
