name = "FTB Chunks (Fabric)"
filename = "ftb-chunks-fabric-1801.3.4-build.127.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3627/153/ftb-chunks-fabric-1801.3.4-build.127.jar"
hash-format = "sha1"
hash = "aeb23fc2667e2571beffa7e66a684208d1dd93fe"

[update]
[update.curseforge]
file-id = 3627153
project-id = 472657
