name = "Fabric Waystones"
filename = "wraith-waystones-2.4.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/sTZr7NVo/versions/2.4.0/wraith-waystones-2.4.0.jar"
hash-format = "sha1"
hash = "c9df7900f7a626bca093d41a5227bde7d15bfdb2"

[update]
[update.modrinth]
mod-id = "sTZr7NVo"
version = "6jAinwnq"
