name = "GeckoLib"
filename = "geckolib-fabric-1.18-3.0.35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3667/587/geckolib-fabric-1.18-3.0.35.jar"
hash-format = "sha1"
hash = "93afc357e984595d6d5e40aa3632bced32b5e318"

[update]
[update.curseforge]
file-id = 3667587
project-id = 388172
