name = "Goblin Traders (Fabric)"
filename = "goblin-traders-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3717/825/goblin-traders-1.5.1.jar"
hash-format = "sha1"
hash = "fe3de9d8e42badf4a01726d0026a8423508beac4"

[update]
[update.curseforge]
file-id = 3717825
project-id = 534373
