name = "Greater Eye of Ender [FABRIC]"
filename = "GreaterEye-Fabric-1.18.1-1.3.21.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3637/759/GreaterEye-Fabric-1.18.1-1.3.21.jar"
hash-format = "sha1"
hash = "3d68cdc782e53c2f382b5c16164a7f4357c9f211"

[update]
[update.curseforge]
file-id = 3637759
project-id = 376207
