name = "Hand Over Your Items (Fabric)"
filename = "handoveryouritems-fabric_1.18.x-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/224/handoveryouritems-fabric_1.18.x-1.3.jar"
hash-format = "sha1"
hash = "d44599a1d4a84f1c7d4e536150b99d552f49ba09"

[update]
[update.curseforge]
file-id = 3542224
project-id = 530057
