name = "Iceberg [Fabric]"
filename = "Iceberg-1.18.1-fabric-1.0.38.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3597/368/Iceberg-1.18.1-fabric-1.0.38.jar"
hash-format = "sha1"
hash = "5c9712b51f431fb9d8148dc1aad4cab307ad5e30"

[update]
[update.curseforge]
file-id = 3597368
project-id = 539382
