name = "Lenient Stack Size"
filename = "lenientstacksize-1.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3567/277/lenientstacksize-1.3.0.jar"
hash-format = "sha1"
hash = "bde09c1546bee811f5f78aa002b32d9758db4ad3"

[update]
[update.curseforge]
file-id = 3567277
project-id = 523776
