name = "Macaw's Lights and Lamps"
filename = "mcw-lights-1.0.2fabric-mc1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3648/407/mcw-lights-1.0.2fabric-mc1.18.1.jar"
hash-format = "sha1"
hash = "6308101c2f4d0174f1e1e57a14ed3db20e7be02d"

[update]
[update.curseforge]
file-id = 3648407
project-id = 502372
