name = "More Villagers [Fabric]"
filename = "morevillagers-FABRIC-1.18.1-3.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3606/177/morevillagers-FABRIC-1.18.1-3.1.1.jar"
hash-format = "sha1"
hash = "4d32e38b96e53c0a9ec88b954834e130a7e975f8"

[update]
[update.curseforge]
file-id = 3606177
project-id = 486080
