name = "myLoot"
filename = "myloot-1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3687/825/myloot-1.8.jar"
hash-format = "sha1"
hash = "877f317197a8b4f519a65660239aeb61bfa249cd"

[update]
[update.curseforge]
file-id = 3687825
project-id = 582459
