name = "myLoot"
filename = "myloot-2.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/53/myloot-2.0.1.jar"
hash-format = "sha1"
hash = "afe6c15bce9ff399013967db8c54edbccec33646"

[update]
[update.curseforge]
file-id = 3707053
project-id = 582459
