name = "myLoot"
filename = "myloot-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/417/myloot-2.0.2.jar"
hash-format = "sha1"
hash = "064f975903645e84987e55d819abf5615a3e70cf"

[update]
[update.curseforge]
file-id = 3725417
project-id = 582459
