name = "myLoot"
filename = "myloot-2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3727/940/myloot-2.1.jar"
hash-format = "sha1"
hash = "dfcbc1e2eea1ab6b8b1bfb974491e13661347da6"

[update]
[update.curseforge]
file-id = 3727940
project-id = 582459
