name = "Name Pain"
filename = "namepain-1.4.0 fabric-1.17.x.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3352/348/namepain-1.4.0%20fabric-1.17.x.jar"
hash-format = "sha1"
hash = "58ca86413dc465f5d1a1b36bd8a8fd0bb9a84e47"

[update]
[update.curseforge]
file-id = 3352348
project-id = 366263
