name = "No More Ender Pearl Damage"
filename = "no-pearl-damage-1.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/918/no-pearl-damage-1.1.2.jar"
hash-format = "sha1"
hash = "91148686bec4b4310f9e780b01d4f5fcbe313a10"

[update]
[update.curseforge]
file-id = 3542918
project-id = 545580
