name = "Numismatic Overhaul"
filename = "numismatic-overhaul-0.1.8+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ZXm8hVxN/versions/0.1.8+1.18/numismatic-overhaul-0.1.8%2B1.18.jar"
hash-format = "sha1"
hash = "eb956f85e0192fa5183cd38fd87a6b5695e087e3"

[update]
[update.modrinth]
mod-id = "ZXm8hVxN"
version = "4W6fpplJ"
