name = "Numismatic Overhaul"
filename = "numismatic-overhaul-0.1.10+1.18.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/ZXm8hVxN/versions/0.1.10+1.18/numismatic-overhaul-0.1.10%2B1.18.jar"
hash-format = "sha1"
hash = "557786511c6a393c7cd095e2949ea6934b7211d1"

[update]
[update.modrinth]
mod-id = "ZXm8hVxN"
version = "wm7yiU9I"
