name = "Passive Endermen (Fabric)"
filename = "passiveendermen-fabric_1.18.x-2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3651/98/passiveendermen-fabric_1.18.x-2.1.jar"
hash-format = "sha1"
hash = "32b081ef6ab3955cfc60de9b621af0a4ab3361e5"

[update]
[update.curseforge]
file-id = 3651098
project-id = 580907
