name = "Patchouli"
filename = "Patchouli-1.18.1-65-FABRIC.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/nU0bVIaL/versions/1.18.1-65-fabric/Patchouli-1.18.1-65-FABRIC.jar"
hash-format = "sha1"
hash = "8394d0e39f847d2ca548830ffd2f67684a7b9f1f"

[update]
[update.modrinth]
mod-id = "nU0bVIaL"
version = "OUi0L7mI"
