name = "Pling"
filename = "pling-1.5.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/632/pling-1.5.0.jar"
hash-format = "sha1"
hash = "352ad6d9b5f579c4f0f9c0bee0342cda7c941aff"

[update]
[update.curseforge]
file-id = 3550632
project-id = 365521
