name = "Public Gui Announcement"
filename = "Public GUI Announcement-fabric-1.18.1-3.2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/870/Public%20GUI%20Announcement-fabric-1.18.1-3.2.0.0.jar"
hash-format = "sha1"
hash = "39f887697c39859f77e0370b41b581036fc116ec"

[update]
[update.curseforge]
file-id = 3605870
project-id = 341727
