name = "Skinned Lanterns (Fabric)"
filename = "skinnedlanterns-1.2.0+build.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3586/429/skinnedlanterns-1.2.0+build.12.jar"
hash-format = "sha1"
hash = "85ca0060c7a17d44a6b6f60d0e1c5e7470b34c8b"

[update]
[update.curseforge]
file-id = 3586429
project-id = 422527
