name = "spark"
filename = "spark-1.8.14-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/l6YH9Als/versions/1.8.14-fabric/spark-1.8.14-fabric.jar"
hash-format = "sha1"
hash = "597ce2e6aa61c4e99b2674af489335b25adb3b48"

[update]
[update.modrinth]
mod-id = "l6YH9Als"
version = "VkKsarbC"
