name = "SpoornPacks"
filename = "spoornpacks-3.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/783/spoornpacks-3.6.jar"
hash-format = "sha1"
hash = "48ea7fbe0679daf0f9c753ec768d6d2b774ea7e7"

[update]
[update.curseforge]
file-id = 3670783
project-id = 577442
