name = "Subterrestrial (Fabric)"
filename = "Subterrestrial-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/713/Subterrestrial-1.0.2.jar"
hash-format = "sha1"
hash = "6a59d578b1dfc581b45084bae5d37c36ac1bf46b"

[update]
[update.curseforge]
file-id = 3670713
project-id = 575588
