name = "ThonkUtil"
filename = "thonkutil-2.12.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3709/203/thonkutil-2.12.0+1.18.jar"
hash-format = "sha1"
hash = "26c7bd853e4a0b9880d3a43a3c18f180693c04a8"

[update]
[update.curseforge]
file-id = 3709203
project-id = 536648
