name = "ThonkUtil"
filename = "thonkutil-2.7.1+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3614/0/thonkutil-2.7.1+1.18.jar"
hash-format = "sha1"
hash = "d47323725baa71cb3b4738f6c9ad01d535117cdc"

[update]
[update.curseforge]
file-id = 3614000
project-id = 536648
