name = "Trading Post [Fabric]"
filename = "TradingPost-v3.1.2-1.18.1-Fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3569/713/TradingPost-v3.1.2-1.18.1-Fabric.jar"
hash-format = "sha1"
hash = "e4296b90a1db829effaab69940445268f2f6f296"

[update]
[update.curseforge]
file-id = 3569713
project-id = 547472
