name = "Trident Revision"
filename = "trident_revision-1.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3542/981/trident_revision-1.0.4.jar"
hash-format = "sha1"
hash = "7097dd9d4ee8434a8110778d27c8c2b24ac7744c"

[update]
[update.curseforge]
file-id = 3542981
project-id = 495014
