name = "VanitySlots"
filename = "VanitySlots-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3616/134/VanitySlots-1.1.1.jar"
hash-format = "sha1"
hash = "dcd3b992b5da11493150435a6a3e0c599e594a8c"

[update]
[update.curseforge]
file-id = 3616134
project-id = 570109
