name = "Void Totem (Fabric)"
filename = "voidtotem-fabric-1.18.2-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3686/508/voidtotem-fabric-1.18.2-1.3.1.jar"
hash-format = "sha1"
hash = "88b6e6ce99bc16e783ba64b55619b529ca37a141"

[update]
[update.curseforge]
file-id = 3686508
project-id = 456137
