name = "VoidZ"
filename = "voidz-1.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/628/voidz-1.0.6.jar"
hash-format = "sha1"
hash = "f5e04f1d2f1ffa014fb9f4286bd913e1147df249"

[update]
[update.curseforge]
file-id = 3683628
project-id = 486971
