name = "Void Totem (Fabric)"
filename = "voidtotem-fabric-1.18.1-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/832/voidtotem-fabric-1.18.1-1.2.0.jar"
hash-format = "sha1"
hash = "6aeabc6d23842fff590d911c0d45c0ec265daef8"

[update]
[update.curseforge]
file-id = 3680832
project-id = 456137
