name = "XL Packets Fabric"
filename = "xlpackets-2.1-1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3527/187/xlpackets-2.1-1.17.1.jar"
hash-format = "sha1"
hash = "de31cbca7e031cdd7a4cd90057d8bfa29aa9a2bf"

[update]
[update.curseforge]
file-id = 3527187
project-id = 390168
