name = "Xtra Arrows"
filename = "Xtra Arrows v1.7.4 FABRIC MC1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3639/472/Xtra%20Arrows%20v1.7.4%20FABRIC%20MC1.18.jar"
hash-format = "sha1"
hash = "a2bc9cc4c3a2311484af5790f2f57b07d5d522c8"

[update]
[update.curseforge]
file-id = 3639472
project-id = 566441
